name: Deploy

on: [push] # workflow_dispatch pour action manuelle

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan 51.178.30.27 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          
      - run: ssh debian@51.178.30.27 "cd /usr/share/nginx/html/nextjs && git pull"
      - run: ssh debian@51.178.30.27 "cd /usr/share/nginx/html/nextjs && npm i"
      - run: ssh debian@51.178.30.27 "cd /usr/share/nginx/html/nextjs && npm run build"
      - run: ssh debian@51.178.30.27 "cd /usr/share/nginx/html && pm2 startOrReload ecosystem.config.js"