name: Deploy

on: [push] # workflow_dispatch pour action manuelle

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          ssh-keyscan 51.178.30.27 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          
      - run: ssh admin@51.178.30.27 "ls"